#!/bin/sh
if [ "$#" -ne 2 ] ; then
    echo $0 "<resource-group> <server-ip>"
    exit 1
fi

VMS=/tmp/$1_vms
azure vm list $1|tail -n+5 |head -n-1 |awk '{print $2}' > $VMS

vi $VMS

VMT=/tmp/$1_vms_deploy.json
cat $VMS| ./genAgentTemplate $2 >$VMT
azure group deployment create $1 -f $VMT -n deployMonitorAgent
