#!/usr/bin/env perl

use 5.010;

my $serverIp = shift;

my @vms=<>;
my $resources;
foreach (@vms){
    chomp;
    my $templateResource = << "EOF";
    {
      "apiVersion": "2015-06-15",
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "name": "$_/installMonitoringAgent",
      "location": "Southeast Asia", 
      "properties": {
            "publisher": "Microsoft.OSTCExtensions",
            "type": "CustomScriptForLinux",
            "typeHandlerVersion": "1.4",
            "settings":{
                "fileUris": ["https://raw.githubusercontent.com/karataliu/monicake/master/run"],
                "commandToExecute": "[concat('./run -v agent ', parameters('serverIp'))]"
            }
      }
    },
EOF
    $resources .= $templateResource;
}

chomp($resources); chop($resources);

my $fullTemplate = << "EOF";
{
  "\$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "serverIp":{
        "type": "string",
        "metadata": {
          "description": "server ip."
        },
        "defaultValue": "$serverIp"
    }
  },
  "resources": [
$resources
  ]
}
EOF

say $fullTemplate;
