#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
use JSON::RPC::Legacy::Client;

my $client      = new JSON::RPC::Legacy::Client;
my $endpoint    = shift || 'http://doliuwo2mon.southeastasia.cloudapp.azure.com/zab/';
my $uri         = $endpoint."api_jsonrpc.php";

sub callrpc
{
    my $callobj = shift;
    my $res = $client->call($uri, $callobj);

    if($res) {
        if ($res->is_error) {
            say "Error : ", $res->error_message;
            exit(1);
        }
        else {
            return $res->result;
        }
    }
    else {
        say "Error code: ", $client->status_line;
        exit(2);
    }
}

my $authRequest = 
{
    "jsonrpc", "2.0",
    "method", "user.login",
    "params", {
        "user", "Admin",
        "password", "zabbix"
    },
    "id", 0,
    "auth", undef
};

my $token = callrpc($authRequest);

open FL,'<','templateAzureVmLinux.xml';
my $xml;
{
    local $/ = undef;
    $xml = <FL>;
}
close FL;

my $importRequest  = 
{
    "jsonrpc", "2.0",
    "method", "configuration.import",
    "params", {
        "format", "xml",
        "rules", {
            "templates", {
                "createMissing", 1
            },
            "items", {
                "createMissing", 1
            },
            "triggers",{
                "createMissing", 1
            },
        },
        "source", "$xml"
    },
    "auth", "$token",
    "id", 1
};

callrpc($importRequest);

