#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
use JSON::RPC::Legacy::Client;

my $client      = new JSON::RPC::Legacy::Client;
my $endpoint    = shift || 'http://doliuwo2mon.southeastasia.cloudapp.azure.com/zab/';
my $uri         = $endpoint."api_jsonrpc.php";

sub callrpc
{
    my $callobj = shift;
    my $res = $client->call($uri, $callobj);

    if($res) {
        if ($res->is_error) {
            print "Error : ", $res->error_message;
            exit(1);
        }
        else {
            return $res->result;
        }
    }
    else {
        say "Error code: ", $client->status_line;
        exit(2);
    }
}

my $authRequest = 
{
    "jsonrpc", "2.0",
    "method", "user.login",
    "params", {
        "user", "Admin",
        "password", "zabbix"
    },
    "id", 1,
    "auth", undef
};

say callrpc($authRequest);