#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
use Getopt::Std;
use Data::Dumper;

use constant {
    LOGDEBUG  => 1,
    LOGINFO   => 2,
    LOGWARN   => 3
};


$Getopt::Std::STANDARD_HELP_VERSION = 1;
our $VERSION    = 0.1;
my %opts;
exit(1) if !getopts('vnq', \%opts);
my $optVerbose  = $opts{'v'} ? 1 : ($opts{'q'} ? 3 : 2 );
my $optDryrun   = $opts{'n'};
my $optType     = shift || "help";

sub HELP_MESSAGE    { say "$0 [-nvq] <server|agent> ";   }
sub VERSION_MESSAGE { say "monicake version $VERSION";  }

sub info
{
    my $msg     = shift;
    my $level   = shift || LOGINFO;

    return if ($optVerbose > $level);
    say "[MONICAKE] $msg";
}

sub runCmd
{
    my $cmd = shift;
    if ($optVerbose <= LOGINFO && $cmd !~ />/) { $cmd .= " >/dev/null"; }

    info "Run command:\n$cmd", LOGDEBUG;
    return 0 if $optDryrun;

    my $ret = system($cmd);
    if ($ret){
        info "Return code is $ret";
    }

    return $ret;
}

sub installPackage
{
    my $packageLine = join(" ", @_);
    my $cmd         = "DEBIAN_FRONTEND=noninteractive apt-get -y install $packageLine";

    info "Begin install packages:$packageLine";

    my $ret = runCmd($cmd);
    if (!$ret){
        info("Install succeed.");
    }else{
        info("Install failed.");
    }
}

my $zabbixDb        = "zabbixdb";
my $zabbixUser      = "zabbix";
my $zabbixPassword  = "pabbix";

my $confServerApachePhp = << 'EOM';
php_value max_execution_time 300
php_value memory_limit 128M
php_value post_max_size 16M
php_value upload_max_filesize 2M
php_value max_input_time 300
php_value date.timezone Asia/Shanghai
EOM

my $confServerPhp = << "EOM";
<?php
global \$DB;

\$DB['TYPE']     = 'MYSQL';
\$DB['SERVER']   = 'localhost';
\$DB['PORT']     = '0';
\$DB['DATABASE'] = '$zabbixDb';
\$DB['USER']     = '$zabbixUser';
\$DB['PASSWORD'] = '$zabbixPassword';

\$ZBX_SERVER      = 'localhost';
\$ZBX_SERVER_PORT = '10051';
\$ZBX_SERVER_NAME = '';
\$IMAGE_FORMAT_DEFAULT = IMAGE_FORMAT_PNG;
?>
EOM

my $dbSetup = << "EOM";
create database $zabbixDb character set utf8 collate utf8_bin;
grant all privileges on $zabbixDb.* to $zabbixUser\@localhost identified by '$zabbixPassword';
EOM

my $confServer = << "EOM";
DBHost=localhost
DBName=$zabbixDb
DBUser=$zabbixUser
DBPassword=$zabbixPassword
EOM

my $confDefault = << 'EOM';
START=yes
CONFIG_FILE="/etc/zabbix/zabbix_server.conf"
EOM

# MAIN
if ($optType eq "agent"){
    info("Begin install Zabbix Agent.");
    installPackage("zabbix-agent");
}elsif ($optType eq "server"){
    info("Begin install Zabbix Server.");
    installPackage("zabbix-server-mysql zabbix-frontend-php php5-mysql");
    info("Configure apache.");
    runCmd("echo 'Alias /z /usr/share/zabbix' > /etc/apache2/sites-available/zabbix.conf");
    runCmd("a2ensite zabbix");
    runCmd("echo '$confServerApachePhp' > /etc/apache2/conf-available/php-zabbix.conf");
    runCmd("a2enconf php-zabbix");

    info("Configure db.");
    #runCmd("mysqladmin -u root password p1");
    runCmd("mysql <<EOF\n$dbSetup\nEOF");
    runCmd("zcat /usr/share/zabbix-server-mysql/{schema,images,data}.sql.gz |mysql -uzabbix -pzabbix zabbix");
    runCmd("cat >/etc/zabbix/zabbix.conf.php <<EOF\n$confServerPhp\nEOF");
    runCmd("cat >/etc/zabbix/zabbix_server.conf <<EOF\n$confServer\nEOF");
    runCmd("cat >/etc/default/zabbix-server <<EOF\n$confDefault\nEOF");

    runCmd("service apache2 restart");
    info("Done.");
} else {
    &HELP_MESSAGE;
}



