#!/usr/bin/env perl

use strict;
use warnings;
use 5.010;
use Getopt::Std;
$Getopt::Std::STANDARD_HELP_VERSION = 1;

our $VERSION = 0.1;
my %opts;
if(!getopts('vn', \%opts)){
    exit(1);
}

my $optVerbose  = $opts{'v'};
my $optDryrun   = $opts{'n'};
my $optType     = shift || "help";

sub info
{
    return if !$optVerbose;
    my $msg = shift;
    say "[MONICAKE] $msg";
}

sub runCmd
{
    my $cmd = shift;
    info "Run command:";

    say $cmd if $optVerbose || $optDryrun;
    return 0 if $optDryrun;

    if (!$optVerbose) { $cmd += ">/dev/null"; }
    my $ret = system($cmd);
    if ($ret){
        info "Return code is $ret";
    }

    return $ret;
}

sub installPackage
{
    my $packageLine = join(" ", @_);
    my $cmd         = "DEBIAN_FRONTEND=noninteractive apt-get -y install $packageLine";
    my $ret;

    info "Begin install packages:$packageLine";

    $ret = runCmd($cmd);
    if (!$ret){
        info("Install succeed.");
    }else{
        info("Install failed.");
    }
}

my $confServerApachePhp = << 'EOM';
php_value max_execution_time 300
php_value memory_limit 128M
php_value post_max_size 16M
php_value upload_max_filesize 2M
php_value max_input_time 300
php_value date.timezone Asia/Shanghai
EOM

my $confServerPhp = << 'EOM';
<?php
global $DB;

$DB['TYPE']     = 'MYSQL';
$DB['SERVER']   = 'localhost';
$DB['PORT']     = '0';
$DB['DATABASE'] = 'zabbix';
$DB['USER']     = 'root';
$DB['PASSWORD'] = 'p1';

$ZBX_SERVER      = 'localhost';
$ZBX_SERVER_PORT = '10051';
$ZBX_SERVER_NAME = '';
$IMAGE_FORMAT_DEFAULT = IMAGE_FORMAT_PNG;
?>
EOM

my $dbSetup = << 'EOM';
create database zabbix character set utf8 collate utf8_bin;
grant all privileges on zabbix.* to zabbix@localhost identified by 'zabbix';
EOM

sub HELP_MESSAGE
{
    say "$0 [-nv] <server|agent> ";
}

sub VERSION_MESSAGE
{
    say "monicake version 0.1";
}

# MAIN

if ($optType eq "agent"){
    info("Begin install Zabbix Agent.");
    installPackage("zabbix-agent");
}elsif ($optType eq "server"){
    info("Begin install Zabbix Server.");
    installPackage("zabbix-server-mysql zabbix-frontend-php php5-mysql");
    runCmd("echo 'Alias /z /usr/share/zabbix' > /etc/apache2/sites-available/zabbix.conf");
    runCmd("a2ensite zabbix");
    runCmd("echo '$confServerApachePhp' > /etc/apache2/conf-available/php-zabbix.conf");
    runCmd("a2enconf php-zabbix");
    runCmd("mysqladmin -u root password p1");
    runCmd("mysql -uroot -pp1 <<EOF\n$dbSetup\nEOF");
    runCmd("zcat /usr/share/zabbix-server-mysql/schema.sql.gz |mysql -uroot -pp1 zabbix");
    runCmd("zcat /usr/share/zabbix-server-mysql/images.sql.gz |mysql -uroot -pp1 zabbix");
    runCmd("zcat /usr/share/zabbix-server-mysql/data.sql.gz |mysql -uroot -pp1 zabbix");
    my $b=$confServerPhp;
    $b=~s/\$/\\\$/g;
    runCmd("cat >/etc/zabbix/zabbix.conf.php <<EOF\n$b\nEOF");
    runCmd("service apache2 restart");
} else {
    &HELP_MESSAGE;
}



